'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Board

    '''<summary>
    '''hdnGoback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnGoback As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnScrollType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnScrollType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBoardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBoardName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''coverPicDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coverPicDiv As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgOwnedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgOwnedBy As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''boardNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boardOwnerHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardOwnerHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''mainDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''messageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPreviousBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousBoard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hyperlinkDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlinkDistrict As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''areaHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btnNextBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextBoard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ThermometerSlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThermometerSlider As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''lblBoardLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoardLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountLeft As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBoardersIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoardersIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnComment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblCommentsBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommentsBottom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnRecommend As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblRecommendsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecommendsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnBoost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBoost As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divImageWatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divImageWatch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divImageStopWatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divImageStopWatch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnWatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWatch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnStopWatching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStopWatching As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblWatches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWatches As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWatchesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWatchesBottom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mediaLinksTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediaLinksTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''filesUploadedTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filesUploadedTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''crowdBoardTeamLinkTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardTeamLinkTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''playDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents playDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadMediaPlayer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMediaPlayer1 As Global.Telerik.Web.UI.RadMediaPlayer

    '''<summary>
    '''lblCrowdBoardType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCrowdBoardType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSeeking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeeking As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPricedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPricedFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moreInfoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moreInfoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mediaLinksDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediaLinksDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mediaLinksDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediaLinksDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''fileDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''filesUploadedDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filesUploadedDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''RadChart1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadChart1 As Global.Telerik.Web.UI.RadChart

    '''<summary>
    '''RadChart2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadChart2 As Global.Telerik.Web.UI.RadChart

    '''<summary>
    '''crowdBoardTeamDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardTeamDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''crowdBoardTeamRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardTeamRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boardersInDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardersInDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''boardInvestedDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardInvestedDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''boardLevelsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardLevelsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boardIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardIDHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''WCRDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WCRDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''lbtnCloseBoostPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCloseBoostPopup As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccessBoost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessBoost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorBoost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorBoost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBoostContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBoostContent As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnFacebookShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFacebookShare As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnTwitterShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTwitterShare As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbtnCloseBoardComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCloseBoardComments As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSuccessMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''sdBoardsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardsList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardsByArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardsByArea As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdWatchers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdWatchers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdWatching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdWatching As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardComments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUpdates As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardLevels As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdViewBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdViewBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllBoardersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoardersList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdBoardTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdBoardTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRecentActivityOnBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRecentActivityOnBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdFilesUploaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdFilesUploaded As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardMediaLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardMediaLinks As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRecommend As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckRecommend As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRecentCommentsOnBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRecentCommentsOnBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsRecommended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRecommended As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsWatchedOnBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsWatchedOnBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsBoardInvested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsBoardInvested As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdLevelReachedGraph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdLevelReachedGraph As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAmountrRaisedGraph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAmountrRaisedGraph As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsWCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsWCR As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow2 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''loginRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginRadWindow As Global.Telerik.Web.UI.RadWindow
End Class
