'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BoarderRequests

    '''<summary>
    '''lnkbtnConnect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnConnect As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnInvitations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnInvitations As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnCrowdTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnCrowdTeam As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MultiViewBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiViewBoarder As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewConnect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewConnect As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''boardersRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardersRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ViewCrowdTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewCrowdTeam As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''crowdBoardTeamRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardTeamRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ViewInvitations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewInvitations As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''crowdBoardInvitationsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardInvitationsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''sdPendingRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPendingRequests As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRejectRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRejectRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsCrowdBoardInvites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCrowdBoardInvites As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsCrowdBoardTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCrowdBoardTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRejectCrowdboardTeamRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRejectCrowdboardTeamRequest As Global.System.Web.UI.WebControls.SqlDataSource
End Class
