'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class rwAddExtra

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''boardImageDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardImageDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProfile As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMessageAddExtra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageAddExtra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackgroungPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackgroungPicture As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCoverPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCoverPicture As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBoardFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBoardFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnDesign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnDesign As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnMoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnMoreInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnMediaLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnMediaLinks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnUploadFiles As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnCrowdBoardTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCrowdBoardTeam As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnPreview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''designView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents designView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessageDesign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageDesign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rauBackgroundPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rauBackgroundPicture As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''rauCoverPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rauCoverPicture As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''txtYoutubeVideoUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYoutubeVideoUrl As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnAddToCrowdboardDesign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddToCrowdboardDesign As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''backgroundDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents backgroundDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''coverPicDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coverPicDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''moreInfoView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moreInfoView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessageMoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageMoreInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''reCreatePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reCreatePage As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''btnSaveMoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMoreInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mediaLinksView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediaLinksView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessageMediaLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageMediaLinks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMediaLinkName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaLinkName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvMediaLinksName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMediaLinksName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtMediaLinkUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaLinkUrl As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvMediaLinksUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMediaLinksUrl As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnAddMediaLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMediaLink As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rgBoardMediaLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgBoardMediaLinks As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''uploadFilesView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadFilesView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMesaageUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMesaageUploadFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rauBoardFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rauBoardFiles As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''rgBoardFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgBoardFiles As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''crowdBoardTeamView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardTeamView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessageCrowdboardTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageCrowdboardTeam As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbAllBoardersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAllBoardersList As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rfvBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvBoarder As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtRequestTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestTitle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtRequestDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestDescription As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnSendrRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendrRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''previewView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previewView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''sdUpdateUrlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUpdateUrlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardFiles As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardMediaLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardMediaLinks As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllBoardersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoardersList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdBoardTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdBoardTeam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUpdateCreatePageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUpdateCreatePageUrl As Global.System.Web.UI.WebControls.SqlDataSource
End Class
