'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateBoarders

    '''<summary>
    '''lblCrowdboardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCrowdboardName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEdit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnManage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnManage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnUpdate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''messageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnUpdates As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnBodersin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBodersin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnWatching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnWatching As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rmpUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmpUpdates As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''rpvUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvUpdates As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''profilePic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profilePic As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPost As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''postRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postRadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ownerPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ownerPosts As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''rpvBodersin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvBodersin As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessageAddBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageAddBoarder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nonFriendDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nonFriendDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''rpvWatching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvWatching As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''watchBoardDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchBoardDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''sdAllBoardersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoardersList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdWatchBoarders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdWatchBoarders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPosts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdMessageCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdMessageCount As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckBoardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckBoardName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckuserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckuserName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoarders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoarders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdWatchers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdWatchers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardInsiderPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardInsiderPosts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdGetBoardIdDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdGetBoardIdDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdInsiderPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdInsiderPosts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPostReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPostReplies As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCommentOnPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCommentOnPost As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdIRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdIRecommend As Global.System.Web.UI.WebControls.SqlDataSource
End Class
