'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Confirm

    '''<summary>
    '''balancedCreditCardURI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balancedCreditCardURI As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''stripeCardToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stripeCardToken As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnCreatecard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreatecard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreateCardForStripe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCardForStripe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnCloseBalanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCloseBalanced As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSuccessBalanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessBalanced As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorBalanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorBalanced As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFirstNameForCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstNameForCard As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastNameForCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastNameForCard As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCcNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCcNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExpiryMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpiryMonth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExpiryYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpiryYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eligibleForGiftAidTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eligibleForGiftAidTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''cbEligibleForGiftAid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEligibleForGiftAid As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnCreateCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''boardNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''messageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtLevelAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLevelAmount As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFees As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtStandardCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStandardCharge As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtLevelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLevelName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''billingInfoDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents billingInfoDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCity As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtState As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZip As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSsn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnInvest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''balanceurl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balanceurl As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''balanceLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balanceLogo As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''hdnBoardID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBoardID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnLevelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLevelID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAmountInvested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAmountInvested As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sdBillingInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBillingInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdInvestmentDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdInvestmentDetail As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserNameByUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserNameByUserID As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdConfirmedInvestorsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdConfirmedInvestorsDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdInvestmentByStripe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdInvestmentByStripe As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckInvestment As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUsersInfoChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUsersInfoChanges As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdProcessPreApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdProcessPreApproval As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPreApprovalInvestments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPreApprovalInvestments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdGetStandardCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdGetStandardCharge As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBalancedInvestorDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBalancedInvestorDetails As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBalancedOwnerDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBalancedOwnerDetails As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdStripeOwnerDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdStripeOwnerDetails As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdStripeInvestorDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdStripeInvestorDetails As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdGetOwnerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdGetOwnerEmail As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBalancedUserCardInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBalancedUserCardInsert As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdStripeUserCardInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdStripeUserCardInsert As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow
End Class
