'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdnAreaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAreaID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''joinArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents joinArea As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddDistrctHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDistrctHidden As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''districtAddDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtAddDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lbtnCloseDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCloseDistrict As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''districtDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''headPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''areaSeachValueHdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaSeachValueHdn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''liHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liHome As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liCrowdNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCrowdNews As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''isAdminli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isAdminli As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbtlogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtlogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''searchBoardsTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchBoardsTextBox As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''requestsCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requestsCountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boardersRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardersRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''crowdBoardInvitationsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardInvitationsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdates As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''messageRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''countNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents countNotification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''notificationsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notificationsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''recentActivityOnBoardsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentActivityOnBoardsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lbtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''radMultiPageCrowdNewFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMultiPageCrowdNewFull As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lbtnEditDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEditDistricts As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''districtsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lbtnEditAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEditAreas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''userAreasRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userAreasRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''profilePic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profilePic As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblBoarderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoarderID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbluserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbluserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPost As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''messageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fileAttachButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileAttachButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fileAttachRadAsyncUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileAttachRadAsyncUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''postRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postRadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''crowdBoardsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdBoardsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''investmentsSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investmentsSet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCreateBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateBoard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnShowAddBoarderView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnShowAddBoarderView As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnImageAddBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnImageAddBoarder As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''boardersDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardersDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ImageBtnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageBtnShow As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbtnShowAllCrowdNewsView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnShowAllCrowdNewsView As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''crowdNewsUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdNewsUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''crowdNewsDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdNewsDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''rpvAddBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvAddBoarder As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lbtnShowBoarderDetailsViewBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnShowBoarderDetailsViewBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updatePanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelSearch As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblMessageAddBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageAddBoarder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''latestBoardPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents latestBoardPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnSearchDistrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchDistrics As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''searchTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchTextBox As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''surfBoardsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surfBoardsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RadMediaPlayer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMediaPlayer1 As Global.Telerik.Web.UI.RadMediaPlayer

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadScriptBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock2 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''sdBoarders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoarders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserInfo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUsersDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUsersDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdNews As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPosts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoards As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPostReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPostReplies As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCommentOnPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCommentOnPost As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdIRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdIRecommend As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckBoardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckBoardName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckuserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckuserName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdMessages As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdMessageCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdMessageCount As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdNotifications As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRecentActivityOnBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRecentActivityOnBoards As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPendingRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPendingRequests As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRejectRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRejectRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsCrowdBoardInvites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCrowdBoardInvites As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRejectCrowdboardTeamRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRejectCrowdboardTeamRequest As Global.System.Web.UI.WebControls.SqlDataSource
End Class
