'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Profile

    '''<summary>
    '''RadScriptBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock2 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''userBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''coverPic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coverPic As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''profilePic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profilePic As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''userNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pendingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pendingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addUsers As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''messageUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''messageDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageDiv As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''sendMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sendMessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sendMessageRadTexBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sendMessageRadTexBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''sendMessageRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sendMessageRadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cancelRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cancelRadButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''activityLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activityLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''boardfolioLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardfolioLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''myBoardfolioLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBoardfolioLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''districtsLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtsLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''myDistrictsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myDistrictsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''areasLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areasLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''myAreasLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myAreasLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crowdboardsLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdboardsLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MyBoardsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyBoardsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crowdboardsLineupLinkbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdboardsLineupLinkbutton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BoardersLineupLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoardersLineupLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''jobLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jobLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divResides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divResides As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''residesInLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents residesInLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''homeTownLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents homeTownLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''birthdateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthdateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''skillsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents skillsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''websiteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents websiteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aboutMeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aboutMeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''myPassionsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myPassionsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''myDreamsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myDreamsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''messageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents messageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''userNameLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''createdBoardDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createdBoardDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''createProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createProfileImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''createdBoardNameLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createdBoardNameLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateCreated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateCreated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''surfBoardsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surfBoardsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''recentInvestedTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentInvestedTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''investedProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investedProfileImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''investedUserNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investedUserNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''investedHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investedHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''investmentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investmentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boardLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''userLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''recentCommentTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentCommentTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''commentedProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents commentedProfileImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''commentUserNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents commentUserNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''commentBordNameLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents commentBordNameLinkButton As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''commentTextLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents commentTextLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommentDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''watchBoardTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchBoardTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''watchProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchProfileImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''watchUserNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchUserNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''watchBoradNameHyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchBoradNameHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''watchDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents watchDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''recentPostTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentPostTr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''latestPostRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents latestPostRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boardFolioLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardFolioLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boardsInvestedDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardsInvestedDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''districtLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''districtsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtsRepeater As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''areaLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''userAreasRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userAreasRepeater As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''crowdboarderseLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdboarderseLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crowdboardCommandRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crowdboardCommandRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boarderLineupLabelActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boarderLineupLabelActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessageAddBoarder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageAddBoarder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boardersRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardersRepeater As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''sdUserInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserInformation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardersLineUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardersLineUp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUsersDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUsersDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdInvestments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdInvestments As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardFolio As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdActiveBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdActiveBoards As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoarders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoarders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdBoardsInvestedByUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoardsInvestedByUser As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdMessages As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRecentPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRecentPost As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdRcentlyAddedFriend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdRcentlyAddedFriend As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdGetUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdGetUserId As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsCreatedBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCreatedBoard As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsComment As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsInvested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsInvested As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsWatched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsWatched As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckRequest As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsUserEmail As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoards As Global.System.Web.UI.WebControls.SqlDataSource
End Class
