'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''radMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''rpvTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvTop As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''showAllLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents showAllLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''districtDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblMessageSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageSearch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''areasRepeaterDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areasRepeaterDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''areaTitleDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaTitleDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''areaRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''filterDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbtnLatestBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLatestBoards As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnMostActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnMostActive As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnMostWatched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnMostWatched As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnMostRaised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnMostRaised As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel9Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel9Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel8Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel8Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel7Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel7Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel6Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel6Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel5Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel5Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel4Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel4Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel3Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel3Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLevel2Plus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLevel2Plus As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''welcomeDistrictDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcomeDistrictDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''welcomeDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcomeDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''districtNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents districtNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistrictDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrictDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistrictQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrictQuotation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPopulationCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPopulationCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addDistrictRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addDistrictRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''welcomeAreaDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcomeAreaDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAreaNameWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAreaNameWelcome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''areaPopulationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaPopulationLabel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnJoinIncrowdArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJoinIncrowdArea As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''createNewboardDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createNewboardDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''boardsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boardsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pagingDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagingDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblShowPangeNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowPangeNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wordOnStreetDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wordOnStreetDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnViewFullWordOnStreetNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewFullWordOnStreetNews As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''postOnDistrictDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postOnDistrictDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtPostOnDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostOnDistrict As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnPostOnDitrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPostOnDitrict As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''wordOntheStreetRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wordOntheStreetRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''inCrowdLatestDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inCrowdLatestDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnViewFullInCrowdLatest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewFullInCrowdLatest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''postOnAreaDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postOnAreaDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtInCrowdLatestPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInCrowdLatestPost As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnInCrowdLatestPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInCrowdLatestPost As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''inCrowdLatestRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inCrowdLatestRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rpvAllAreaNewsView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvAllAreaNewsView As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''joinAreaLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents joinAreaLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''backFromAllAreaNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents backFromAllAreaNews As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''selectedAreaNameLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedAreaNameLable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrowdLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrowdLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''viewIncrowdLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewIncrowdLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''incrowdPostLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrowdPostLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''radMultiPageMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMultiPageMiddle As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''rpvIncrowdLatest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvIncrowdLatest As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''areaSpecificNewsDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaSpecificNewsDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''rpvViewInCrowd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvViewInCrowd As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''viewInCrowdDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewInCrowdDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''rpvViewInCrowdPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvViewInCrowdPosts As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''areaPostDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaPostDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''userProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userProfileImage As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''userNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''areaSpecificPostTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaSpecificPostTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fileAttachButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileAttachButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fileAttachRadAsyncUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileAttachRadAsyncUpload As Global.Telerik.Web.UI.RadAsyncUpload

    '''<summary>
    '''addAreaSpecificPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAreaSpecificPost As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''areaSpecificNewsDataListPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaSpecificNewsDataListPost As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''sdBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdBoards As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdSearchValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdSearchValue As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsLoadBordByArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsLoadBordByArea As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUserAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUserAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdUpdates As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdDistrictDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdDistrictDesc As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdNewsAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdNewsAll As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdNews As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckBoardName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckBoardName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCheckuserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCheckuserName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdViewIncrowd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdViewIncrowd As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPosts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdNewsDistrictSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdNewsDistrictSpecific As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCrowdNewsAreaSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCrowdNewsAreaSpecific As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdLoadBoardsByLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdLoadBoardsByLevel As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdLoadBoardsMostRaised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdLoadBoardsMostRaised As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdLoadBoardsMostWatched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdLoadBoardsMostWatched As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdLoadBoardsMostActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdLoadBoardsMostActive As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdGetDistrictName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdGetDistrictName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllAreas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdAllBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdAllBoards As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDistricts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdIRecommend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdIRecommend As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdPostReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdPostReplies As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdCommentOnPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdCommentOnPost As Global.System.Web.UI.WebControls.SqlDataSource
End Class
